language: csharp
mono: none
dotnet: 1.0.1
dist: trusty
solution: Aromato.sln
install:
  - nuget restore Aromato.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Aromato.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Aromato.Test/bin/Debug/netcoreapp1.1/Aromato.Test.dll